services:
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    healthcheck:
          test: curl --fail http://localhost:9000/ || exit 1
          interval: 40s
          timeout: 30s
          retries: 3
          start_period: 60s

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
